apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gke-angular-route
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  # Set host to the domain name that you own.
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      # Rewrite the original host header to the host header of Search service
      # in order to redirect requests to gke-angular service.
      authority: gke-angular.default.example.com
    route:
      # knative-ingressgateway is the k8s service created by Knative as the
      # shared gateway of all traffic incoming to the cluster.
      # Basically here we redirect the request to the cluster entry again with
      # updated header "gke-angular.default.example.com" so the request will
      # eventually be directed to Search service.
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
        weight: 100
